language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm-nightly

    include:
      - php: 5.4
        env: COMPOSER_FLAG=--prefer-lowest
      - php: 5.4
        env: COMPOSER_FLAG=--prefer-stable
      - php: 5.5
        env: COMPOSER_FLAG=--prefer-lowest
      - php: 5.5
        env: COMPOSER_FLAG=--prefer-stable
      - php: 5.6
        env: COMPOSER_FLAG=--prefer-lowest
      - php: 5.6
        env: COMPOSER_FLAG=--prefer-stable
      - php: 7.0
        env: COMPOSER_FLAG=--prefer-lowest
      - php: 7.0
        env: COMPOSER_FLAG=--prefer-stable

script:
    - vendor/bin/tester tests/reCAPTCHA -s -p php -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

before_script:
    # Update Composer
    - composer self-update

    # Install Nette Tester
    - composer install --no-interaction --prefer-source
